# placetypes/migrations/0001_initial.py
"""
Initial migration for the placetypes app.

Uses SeparateDatabaseAndState so that:
  - Django's internal state learns about the Type model
  - The SQL only creates the table if it doesn't already exist
    (safe for deployments where the 'types' table was created by places)
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            # State operation: tell Django this model exists
            state_operations=[
                migrations.CreateModel(
                    name='Type',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('aat_id', models.IntegerField(unique=True)),
                        ('parent_id', models.IntegerField(blank=True, null=True)),
                        ('term', models.CharField(max_length=100)),
                        ('term_full', models.CharField(max_length=100)),
                        ('note', models.TextField(max_length=3000)),
                        ('fclass', models.CharField(blank=True, max_length=1, null=True)),
                    ],
                    options={
                        'db_table': 'types',
                        'managed': True,
                    },
                ),
            ],
            # Database operation: only create if missing
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "types" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "aat_id" integer NOT NULL UNIQUE,
                            "parent_id" integer NULL,
                            "term" varchar(100) NOT NULL,
                            "term_full" varchar(100) NOT NULL,
                            "note" text NOT NULL,
                            "fclass" varchar(1) NULL
                        );
                    """,
                    reverse_sql='DROP TABLE IF EXISTS "types";',
                ),
            ],
        ),
    ]
