# Generated by Django 4.1.7 on 2026-04-27 13:45
# Hand-edited: replaced bare RenameIndex operations with SeparateDatabaseAndState
# so that each rename is idempotent (DB-op is conditional SQL; state-op keeps
# Django's automigration detector in sync).

from django.db import migrations, models


def _rename_if_exists(old_name, new_name):
    """Return a RunPython-compatible function that conditionally renames one index.

    Restrictions:
    - The OLD name must exist *in the current schema* — otherwise an
      unqualified ``ALTER INDEX "old"`` would resolve via the connection's
      ``search_path`` and fail with "relation does not exist" even if
      ``pg_indexes`` (which spans all schemas) shows a match elsewhere.
    - The NEW name must not already exist — re-runs after a partial
      apply would otherwise fail with "relation already exists".
    """
    def _run(apps, schema_editor):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM pg_indexes "
                "WHERE indexname = %s AND schemaname = current_schema()",
                [old_name],
            )
            if not cursor.fetchone():
                return
            cursor.execute(
                "SELECT 1 FROM pg_indexes "
                "WHERE indexname = %s AND schemaname = current_schema()",
                [new_name],
            )
            if cursor.fetchone():
                return
            cursor.execute(f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"')
    _run.__name__ = f"rename_{old_name}_to_{new_name}"
    return _run


def _create_index_if_missing(apps, schema_editor):
    """Create types_depth_86dfcc_idx if it doesn't already exist in the
    current schema. Schema-qualified check matches ``_rename_if_exists``."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM pg_indexes "
            "WHERE indexname = %s AND schemaname = current_schema()",
            ["types_depth_86dfcc_idx"],
        )
        if not cursor.fetchone():
            cursor.execute(
                'CREATE INDEX "types_depth_86dfcc_idx" '
                'ON "types" ("depth", "is_place_type")'
            )


class Migration(migrations.Migration):

    dependencies = [
        ("placetypes", "0005_add_confidence_to_typemappinglog"),
    ]

    operations = [
        # ── Rename type-table indexes (idempotent) ──────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_if_exists("types_path_idx", "types_path_93f79d_idx"),
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="type",
                    new_name="types_path_93f79d_idx",
                    old_name="types_path_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_if_exists("types_is_place_type_idx", "types_is_plac_fc7023_idx"),
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="type",
                    new_name="types_is_plac_fc7023_idx",
                    old_name="types_is_place_type_idx",
                ),
            ],
        ),
        # ── Rename type_mapping_log indexes (idempotent) ────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_if_exists("type_mappin_created_idx", "type_mappin_created_b87dcb_idx"),
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="typemappinglog",
                    new_name="type_mappin_created_b87dcb_idx",
                    old_name="type_mappin_created_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _rename_if_exists("type_mappin_source__idx", "type_mappin_source__131433_idx"),
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="typemappinglog",
                    new_name="type_mappin_source__131433_idx",
                    old_name="type_mappin_source__idx",
                ),
            ],
        ),
        # ── AlterField operations ────────────────────────────────────────────
        migrations.AlterField(
            model_name="typemappinglog",
            name="action",
            field=models.CharField(
                choices=[("save", "Save mapping"), ("remove", "Remove mapping")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="typemappinglog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="typemappinglog",
            name="source_vocab",
            field=models.CharField(
                help_text="Source vocabulary: geonames, wikidata, osm_ohm", max_length=20
            ),
        ),
        # ── Add depth composite index (idempotent) ───────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _create_index_if_missing,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="type",
                    index=models.Index(
                        fields=["depth", "is_place_type"],
                        name="types_depth_86dfcc_idx",
                    ),
                ),
            ],
        ),
    ]
