# Generated by Django 4.1.7 on 2025-10-31 06:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_alter_placelink_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='fclasses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('A', 'Administrative Boundary'), ('H', 'Hydrographic'), ('L', 'Area'), ('P', 'Populated Place'), ('R', 'Road / Railroad'), ('S', 'Spot (small feature/building/farm)'), ('T', 'Hypsographic (terrain/elevation)'), ('U', 'Undersea'), ('V', 'Vegetation')], max_length=1), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='placetype',
            name='fclass',
            field=models.CharField(choices=[('A', 'Administrative Boundary'), ('H', 'Hydrographic'), ('L', 'Area'), ('P', 'Populated Place'), ('R', 'Road / Railroad'), ('S', 'Spot (small feature/building/farm)'), ('T', 'Hypsographic (terrain/elevation)'), ('U', 'Undersea'), ('V', 'Vegetation')], max_length=1),
        ),
    ]
