# Generated by Django 4.1.7 on 2026-03-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_alter_place_fclasses_alter_placetype_fclass'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='closematch',
            index=models.Index(fields=['place_a', 'place_b'], name='close_match_place_a_832cab_idx'),
        ),
        migrations.AddIndex(
            model_name='closematch',
            index=models.Index(fields=['task'], name='close_match_task_id_067610_idx'),
        ),
        migrations.AddIndex(
            model_name='closematch',
            index=models.Index(fields=['created_by'], name='close_match_created_fd5e58_idx'),
        ),
    ]
