# Generated by Django 4.1.7 on 2026-08-04 08:47

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_remove_type_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyUnionRecord',
            fields=[
                ('whg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None)),
                ('titles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=list, size=None)),
                ('captured', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'legacy_union_records',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='legacyunionrecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['place_ids'], name='legacy_unio_place_i_d0b72d_gin'),
        ),
    ]
