# Generated by Django 4.1.7 on 2025-08-08 17:32

import django.core.validators
from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
