# Generated by Django 4.1.7 on 2025-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_image_file_user_news_permitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
