# Generated by Django 4.1.7 on 2025-08-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_orcid_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
