# Generated by Django 4.1.7 on 2025-08-16 08:05

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='news_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_token_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
