# Generated by Django 4.1.7 on 2025-08-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_news_permitted_user_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orcid_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid_token_scope',
        ),
    ]
