# Generated by Django 4.1.7 on 2025-08-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_orcid_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_file',
        ),
    ]
