# Generated by Django 4.1.7 on 2025-08-23 07:59

from django.db import migrations
import django_resized.forms
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='news_permitted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid_refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orcid_token_expires_at',
        ),
        migrations.AddField(
            model_name='user',
            name='image_file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 600], upload_to=users.models.user_directory_path),
        ),
    ]
