# Generated by Django 4.1.7 on 2025-09-15 15:45

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_user_news_permitted_remove_user_orcid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_file',
        ),
        migrations.AddField(
            model_name='user',
            name='news_permitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_refresh_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
