# Generated by Django 4.1.7 on 2026-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_welcome_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'normal'), ('group_leader', 'group leader'), ('beta_tester', 'beta tester'), ('superuser', 'superuser')], default='normal', max_length=24),
        ),
    ]
