# Generated by Django 4.1.7 on 2026-07-24 11:56

from django.db import migrations, models


def backfill_email_hash(apps, schema_editor):
    """Populate email_hash for existing users. Uses the real model + hash helper (not the historical
    model) so EncryptedTextField decrypts and the HMAC key/algorithm match runtime lookups exactly.
    The AddField above has already created the column. Idempotent + resumable (per-row update)."""
    from users.models import User, email_lookup_hash
    updated = 0
    for u in User.objects.exclude(email__isnull=True).only('id', 'email').iterator():
        try:
            h = email_lookup_hash(u.email)
        except Exception:
            continue
        if h:
            User.objects.filter(pk=u.pk).update(email_hash=h)
            updated += 1
    print(f"  backfilled email_hash for {updated} user(s)")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.RunPython(backfill_email_hash, noop_reverse),
    ]
