# Generated by Django 4.1.7 on 2026-08-02 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_orcid_link_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=39, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$', 'Enter a GitHub username: letters, digits and single hyphens, up to 39 characters.')]),
        ),
    ]
