# Generated by Django 4.1.7 on 2026-06-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('volume_example', models.CharField(blank=True, max_length=500)),
                ('author_compiler', models.CharField(blank=True, max_length=500)),
                ('publication_years', models.CharField(blank=True, max_length=100)),
                ('region_covered', models.TextField(blank=True)),
                ('current_area', models.CharField(blank=True, max_length=255)),
                ('ccodes', models.JSONField(blank=True, default=list)),
                ('repository', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('scan_status', models.CharField(choices=[('downloadable', 'PDF/text downloadable'), ('fullview', 'Catalogue / full view only'), ('none', 'Not digitised'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('triage', 'In triage'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('ingested', 'Ingested'), ('rejected', 'Rejected'), ('parked', 'Parked')], default='suggested', max_length=20)),
                ('next_action', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('provenance', models.CharField(choices=[('own', 'Own research'), ('community', 'Community recommendation'), ('public', 'Public suggestion form')], default='own', max_length=20)),
                ('recommended_by', models.CharField(blank=True, max_length=255)),
                ('priority_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gap_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('zotero_key', models.CharField(blank=True, db_index=True, max_length=32)),
                ('zotero_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('recommender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
    ]
