# docker-compose-dev-tunnel-db.yml

networks:
  WHG3:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  web:
    networks:
      - WHG3
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile-django.dev
    image: whg3_web
    command: /start
    container_name: web
    volumes:
      - .:/app
    env_file:
      - ./.ssh/.ssh-tunnel
    ports:
      - 8001:8000
    depends_on:
      - redis
      - ssh_tunnel

  webpack:
    networks:
      - WHG3
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./compose/local/webpack/Dockerfile-webpack
    image: whg3_webpack
    container_name: webpack
    logging:
      driver: local
    volumes:
      - .:/app

  redis:
    networks:
      - WHG3
    platform: linux/amd64
    image: redis:bullseye
    container_name: redis
    ports: [6380:6379]

  celery_worker:
    image: whg3_web
    command: /start-celeryworker
    container_name: celery_worker
    networks:
      - WHG3
    volumes:
      - .:/app
    env_file:
      - ./.ssh/.ssh-tunnel
    depends_on:
      - redis
      - ssh_tunnel

  celery_beat:
    image: whg3_web
    command: /start-celerybeat
    container_name: celery_beat
    networks:
      - WHG3
    volumes:
      - .:/app
    env_file:
      - ./.ssh/.ssh-tunnel
    depends_on:
      - redis
      - ssh_tunnel

  flower:
    image: whg3_web
    command: /start-flower
    container_name: flower
    networks:
      - WHG3
    volumes:
      - .:/app
    env_file:
      - ./.ssh/.ssh-tunnel
    ports:
      - 5557:5555
    depends_on:
      - redis
      - ssh_tunnel

  ssh_tunnel:
    image: cagataygurturk/docker-ssh-tunnel
    container_name: ssh_tunnel
    ports:
      - 5434:5434
    networks:
      - WHG3
    volumes:
      - ./.ssh/:/root/ssh:ro
    env_file:
      - ./.ssh/.ssh-tunnel
    restart: unless-stopped      

volumes:
  app:
