services:
  webpack-builder:
    networks:
      - whgazetteer-org_whgazetteer-org
    platform: linux/amd64
    image: node:18
    container_name: webpack_builder_whgazetteer-org_main
    logging:
      driver: local
    env_file:
      - .env/.env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/whgadmin/sites/whgazetteer-org:/app
      - /home/whgadmin/sites/whgazetteer-org/package-lock.json:/app/package-lock.json:ro
    working_dir: /app
    command: >
      sh -c "git config --global --add safe.directory /app &&
             npm install --include=dev --no-save && 
             mkdir -p /app/static && 
             npx webpack --config webpack.config.js"
    cpus: 4.0              # Use multiple cores: minimise build time, which affects other services
    mem_limit: 4096m       # 4GB RAM
    memswap_limit: 4096m

networks:
  whgazetteer-org_whgazetteer-org:
    external: true