services:
  webpack-builder:
    networks:
      - whgazetteer-org_whgazetteer-org
    platform: linux/amd64
    image: node:18
    container_name: webpack_builder_whgazetteer-org_main
    logging:
      driver: local
    env_file:
      - .env/.env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/whgadmin/sites/whgazetteer-org:/app
      - /home/whgadmin/sites/whgazetteer-org/package-lock.json:/app/package-lock.json:ro
    working_dir: /app
    command: >
      sh -c "git config --global --add safe.directory /app &&
             npm install --include=dev --no-save && 
             mkdir -p /app/static && 
             npx webpack --config webpack.config.js"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    cpu_shares: 256            # Low priority (default is 1024)
    mem_swappiness: 0
    blkio_config:
      weight: 100              # Low I/O priority (default is 500)

networks:
  whgazetteer-org_whgazetteer-org:
    external: true