services:
  webpack-builder:
    networks:
      - whgazetteer-org_whgazetteer-org
    platform: linux/amd64
    image: node:18
    container_name: webpack_builder_whgazetteer-org_main
    logging:
      driver: local
    env_file:
      - .env/.env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/whgadmin/sites/whgazetteer-org:/app
      - /home/whgadmin/sites/whgazetteer-org/package-lock.json:/app/package-lock.json:ro
    working_dir: /app
    command: >
      sh -c "git config --global --add safe.directory /app &&
             nice -n 19 npm install --include=dev --no-save && 
             mkdir -p /app/static && 
             nice -n 19 npx webpack --config webpack.config.js"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1536M

networks:
  whgazetteer-org_whgazetteer-org:
    external: true