# Generated by Django 4.1.7 on 2026-07-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectYDoc',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ydoc', serialize=False, to='workbench.workbenchproject')),
                ('state', models.BinaryField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workbench_ydoc',
            },
        ),
    ]
