# Generated by Django 4.1.7 on 2026-07-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_collection_license_rights_statement'),
        ('workbench', '0002_projectydoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbenchproject',
            name='base_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workbenchproject',
            name='doc_type',
            field=models.CharField(choices=[('reconciliation', 'Map your Data (reconciliation)'), ('gazetteer_group', 'Gazetteer Group'), ('place_collection', 'Place Collection'), ('itinerary', 'Itinerary'), ('route', 'Route'), ('network', 'Network')], default='reconciliation', max_length=20),
        ),
        migrations.AddField(
            model_name='workbenchproject',
            name='published_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collection.collection'),
        ),
        migrations.AddField(
            model_name='workbenchproject',
            name='published_network_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workbenchproject',
            name='published_route_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workbenchproject',
            name='source_published_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
