# Generated by Django 4.1.7 on 2026-07-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_workbenchproject_base_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbenchproject',
            name='doc_type',
            field=models.CharField(choices=[('reconciliation', 'Map your Data (reconciliation)'), ('gazetteer_group', 'Gazetteer Group'), ('place_collection', 'Place Collection'), ('itinerary', 'Itinerary'), ('place_record', 'Place record correction'), ('route', 'Route'), ('network', 'Network')], default='reconciliation', max_length=20),
        ),
    ]
