# Generated by Django 4.1.7 on 2026-07-09 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0024_dataset_accept_suggestions'),
        ('places', '0024_remove_type_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workbench', '0005_alter_workbenchproject_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_snapshot', models.JSONField(default=dict)),
                ('base_version', models.CharField(max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('applied_changed', models.JSONField(blank=True, default=list)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_suggestions', to='datasets.dataset')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='places.place')),
                ('proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_suggestions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workbench_record_suggestion',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='recordsuggestion',
            index=models.Index(fields=['status', 'dataset'], name='workbench_r_status_96cbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='recordsuggestion',
            index=models.Index(fields=['place', 'status'], name='workbench_r_place_i_763304_idx'),
        ),
    ]
