# Generated by Django 4.1.7 on 2026-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0006_recordsuggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbenchproject',
            name='doc_type',
            field=models.CharField(choices=[('reconciliation', 'Map your Data (reconciliation)'), ('gazetteer_group', 'Gazetteer Group'), ('place_collection', 'Place Collection'), ('itinerary', 'Itinerary'), ('place_record', 'Place record correction'), ('dataset_edit', 'Gazetteer records correction'), ('route', 'Route'), ('network', 'Network'), ('plato', 'PLATO Tools project')], default='reconciliation', max_length=20),
        ),
    ]
