# Generated by Django 4.1.7 on 2025-10-29 09:30

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0005_auto_20250927_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='2-letter ISO country codes aggregated from linked SpatialEntities.', size=None),
        ),
        migrations.AddField(
            model_name='spatialentity',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='2-letter ISO country codes intersecting the geometry.', size=None),
        ),
        migrations.AddIndex(
            model_name='chrononym',
            index=models.Index(fields=['label'], name='chrononym_label_prefix_idx', opclasses=['text_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='chrononym',
            index=django.contrib.postgres.indexes.GinIndex(fields=['label'], name='chrononym_label_trigram_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='chrononym',
            index=models.Index(fields=['languageTag', 'label'], name='chrononym_lang_label_idx'),
        ),
    ]
