# Generated by Django 4.1.7 on 2025-09-27 15:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0005_auto_20250927_1312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chrononym',
            index=models.Index(fields=['label'], name='chrononym_label_prefix_idx', opclasses=['text_pattern_ops']),
        ),
        migrations.AddIndex(
            model_name='chrononym',
            index=django.contrib.postgres.indexes.GinIndex(fields=['label'], name='chrononym_label_trigram_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='chrononym',
            index=models.Index(fields=['languageTag', 'label'], name='chrononym_lang_label_idx'),
        ),
    ]
