# Generated by Django 4.1.7 on 2025-09-30 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0006_chrononym_chrononym_label_prefix_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='2-letter ISO country codes aggregated from linked SpatialEntities.', size=None),
        ),
        migrations.AddField(
            model_name='spatialentity',
            name='ccodes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, help_text='2-letter ISO country codes intersecting the geometry.', size=None),
        ),
    ]
