# Generated by Django 4.1.7 on 2025-10-01 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0007_period_ccodes_spatialentity_ccodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='outerBounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), blank=True, help_text='Earliest start and latest stop years as [start, stop]', null=True, size=2),
        ),
    ]
