# Generated by Django 4.1.7 on 2025-10-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0008_period_outerbounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='outerBounds',
        ),
    ]
