# Generated by Django 4.1.7 on 2024-11-15 09:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0037_collection_coordinate_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='collection',
            name='doi',
            field=models.BooleanField(default=False, help_text='Indicates if a DOI is associated with this collection'),
        ),
    ]
