# Generated by Django 4.1.7 on 2026-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0039_collection_license_rights_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='adaptations_on_request',
            field=models.BooleanField(default=False, help_text='Licence forbids adaptations, but the rights-holder will consider requests.'),
        ),
        migrations.AddField(
            model_name='collection',
            name='commercial_on_request',
            field=models.BooleanField(default=False, help_text='Licence forbids commercial use, but the rights-holder will consider requests.'),
        ),
    ]
