# Generated by Django 4.1.7 on 2026-09-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0040_collection_adaptations_on_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='license_source',
            field=models.CharField(blank=True, choices=[('contributor_selected', 'Chosen by the contributor'), ('legacy_acceptance', 'Recorded retrospectively: contributor accepted a blanket licence at upload'), ('legacy_notice', 'Recorded retrospectively: licence was displayed at upload but not recorded')], help_text='How this licence came to be recorded.', max_length=32, null=True),
        ),
    ]
