"""Add the ``upstream_terms`` provenance value (place#158). Choices only; no column change."""
# Generated by Django 4.1.7 on 2026-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0041_collection_license_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='license_source',
            field=models.CharField(blank=True, choices=[('contributor_selected', 'Chosen by the contributor'), ('legacy_acceptance', 'Recorded retrospectively: contributor accepted a blanket licence at upload'), ('legacy_notice', 'Recorded retrospectively: licence was displayed at upload but not recorded'), ('upstream_terms', "Recorded retrospectively from the upstream source's published terms")], help_text='How this licence came to be recorded.', max_length=32, null=True),
        ),
    ]
