# Generated by Django 4.1.7 on 2026-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gazetteer_h3_coverage_coarse'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazetteerregistryentry',
            name='web_item',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
