# Generated by Django 4.1.7 on 2026-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gazetteer_download_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazetteerregistryentry',
            name='embargo_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gazetteerregistryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('pending', 'pending'), ('embargoed', 'embargoed'), ('published', 'published')], db_index=True, default='published', help_text="Authorities only (place#162): set to 'embargoed' to hold a fully-indexed gazetteer back from anonymous/non-BETA discovery while it stays usable by can_access_beta staff in the live Atlas BETA UI — see GazetteerRegistryEntry.objects.visible_to(). This is a whg3/Django-level visibility gate ONLY: it does not and cannot restrict direct access to the CRC ES gateway (/api/search, /api/reconcile), which has no per-namespace access control of its own. Where that distinction matters, use the indexing repo's disposable staging ES instead. A push from the ingest pipeline never sets 'embargoed' itself and never overwrites it once set — see GazetteerInventoryView._upsert_one.", max_length=12),
        ),
    ]
