swagger: "2.0"
info:
  version: "1.0.0"
  title: "World Historical Gazetteer"
  description: "API Options"  
paths:
  /api/place/{pk}/:
    get:
      summary: "Get Place Detail"
      description: "Retrieve details of a single place by ID."
      parameters:
        - name: pk
          in: path
          description: "ID of the place"
          required: true
          type: integer
      responses:
        '200':
          description: "Place found"
          schema:
            type: object  # Replace with the actual schema of the response
          examples:
            application/json:
              # Example JSON response for the place detail
        '404':
          description: "Place not found"
          schema:
            type: object  # Replace with the actual schema of the error response
          examples:
            application/json:
              # Example JSON response for a not-found scenario
