apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tiles-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust size as needed based on your tile data
