apiVersion: v1
kind: Service
metadata:
  name: tileserver-gl
spec:
  selector:
    app: tileserver-gl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None  # Optionally you can use None for headless service
