# Generated by Django 4.1.7 on 2025-04-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_downloadfile_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tileset',
        ),
    ]
