# Generated by Django 4.1.7 on 2026-07-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_add_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BetaSnag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('what', models.TextField(blank=True, default='')),
                ('expected', models.TextField(blank=True, default='')),
                ('steps', models.TextField(blank=True, default='')),
                ('feature', models.CharField(blank=True, default='', max_length=80)),
                ('severity', models.CharField(blank=True, choices=[('blocker', 'Blocker'), ('major', 'Major'), ('minor', 'Minor'), ('cosmetic', 'Cosmetic')], default='', max_length=20)),
                ('page_url', models.CharField(blank=True, default='', max_length=500)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('github_url', models.CharField(blank=True, default='', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_snags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'beta_snag',
                'ordering': ['-created'],
            },
        ),
    ]
