# Generated by Django 4.1.7 on 2026-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_sitesetting_id_betasnag'),
    ]

    operations = [
        migrations.AddField(
            model_name='betasnag',
            name='kind',
            field=models.CharField(choices=[('snag', 'Snag'), ('suggestion', 'Suggestion')], default='snag', max_length=16),
        ),
    ]
