# Generated by Django 4.1.7 on 2026-07-27 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_betasnag_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_hash', models.CharField(max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invitation_suppression',
            },
        ),
        migrations.CreateModel(
            name='InvitationSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_hash', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('view', 'Share a page'), ('join', 'Invitation to join')], max_length=8)),
                ('target_url', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invitation_send_log',
            },
        ),
        migrations.AddIndex(
            model_name='invitationsendlog',
            index=models.Index(fields=['sender', 'created'], name='invitation__sender__bbd1fe_idx'),
        ),
    ]
