# Generated by Django 4.1.7 on 2025-10-07 07:33

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m49', models.CharField(max_length=10, unique=True)),
                ('level', models.CharField(max_length=20)),
                ('iso_alpha2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), blank=True, default=list, size=None)),
                ('iso_alpha3', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, size=None)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('hull', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('wikidata', models.CharField(blank=True, max_length=50, null=True)),
                ('wikipedia', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('default_language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, default=list, size=None)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('population_date', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
                ('members', models.ManyToManyField(blank=True, related_name='member_of', to='regions.region')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='regions.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(help_text='Base ISO language code', max_length=3)),
                ('variant', models.CharField(blank=True, help_text="Optional language variant (e.g., 'tarask', 'Hant')", max_length=20)),
                ('qualifier', models.CharField(blank=True, help_text="Optional qualifier for the label (e.g., 'UN', 'official', 'old', 'short')", max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='regions.region')),
            ],
            options={
                'unique_together': {('region', 'lang', 'variant', 'qualifier')},
            },
        ),
    ]
