apiVersion: apps/v1
kind: Deployment
metadata:
  name: vespa-config
  labels:
    app: vespa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vespa
      role: config
  template:
    metadata:
      labels:
        app: vespa
        role: config
    spec:
      containers:
        - name: vespa-config
          image: vespa-engine/vespa
          ports:
            - containerPort: 19071
          env:
            - name: VESPA_ZOOKEEPER_HOST
              value: "vespa-zookeeper"
---
apiVersion: v1
kind: Service
metadata:
  name: vespa-config
spec:
  selector:
    app: vespa
    role: config
  ports:
    - protocol: TCP
      port: 19071
      targetPort: 19071
