# Generated by Django 4.1.7 on 2024-11-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_area_bbox_country_bbox'),
        ('resources', '0003_alter_resource_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='doi',
            field=models.BooleanField(default=False, help_text='Indicates if a DOI is associated with this resource'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='regions',
        ),
        migrations.AddField(
            model_name='resource',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='resources', to='areas.area'),
        ),
    ]
