# Generated by Django 4.1.7 on 2025-08-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_doi_remove_resource_regions_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['public'], name='resources_public_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(condition=models.Q(('featured__isnull', False)), fields=['featured'], name='resources_featured_idx'),
        ),
    ]
