# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff/
name: codespell_and_ruff
on:
  push:
    # branches: [main, staging]
  pull_request:
    # branches: [main, staging]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell --ignore-words-list="ans,decription,hart,scenarion,thisy"
        --skip="./datasets/static/hashes/parents.py,./v3_commits.txt,./whg/static/*,*.js,*.json,*.map,*.pdf,*.po,*.sql,*.tsv"
    - run: ruff check --output-format=github --select=E9,F63,F7,F82 --target-version=py310
        --extend-exclude=insert.py,task_utils.py
