name: Update version badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. Read version and set as output
      - name: Read version
        id: ver
        run: |
          # Read version from file
          VERSION_VAL=$(cat VERSION)
          # Set as step output (for use later)
          echo "version=$VERSION_VAL" >> $GITHUB_OUTPUT
      
      # 2. Generate VERSION-BADGE.svg
      - name: Generate VERSION-BADGE.svg
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          LABEL="World Historical Gazetteer"
          LABEL_WIDTH=200
          VALUE_WIDTH=60
          TOTAL_WIDTH=$((LABEL_WIDTH + VALUE_WIDTH))
          COLOR="#4c1"
          
          cat > VERSION-BADGE.svg <<'EOF'
<svg xmlns="http://www.w3.org/2000/svg" width="260" height="20">
  <linearGradient id="b" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <mask id="a">
    <rect width="260" height="20" rx="3" fill="#fff"/>
  </mask>
  <g mask="url(#a)">
    <rect width="200" height="20" fill="#555"/>
    <rect x="200" width="60" height="20" fill="#4c1"/>
    <rect width="260" height="20" fill="url(#b)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" font-size="11">
    <text x="100" y="14">World Historical Gazetteer</text>
    <text x="230" y="14">vVERSION_PLACEHOLDER</text>
  </g>
</svg>
EOF
          
          sed -i "s/VERSION_PLACEHOLDER/$VERSION/" VERSION-BADGE.svg
      
      # 3. Commit badge
      - name: Commit badge
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add VERSION-BADGE.svg
          git commit -m "Update version badge" || echo "No changes to commit"
          git push
